language: ruby
cache: bundler
dist: bionic
services:
  - docker
before_install:
  - travis_retry docker pull shopify/toxiproxy
  - travis_retry docker run --net=host -d shopify/toxiproxy
  - travis_retry gem update --system --force
  - travis_retry gem install bundler --no-document
before_script:
  - export RSPEC_SEED=$(ruby -e "print rand(0xFFFF)")
  - export RSPEC_FORMATTER=progress
script:
  - travis_retry bundle exec rake
matrix:
  include:
    - rvm: 2.5.7
    - rvm: 2.6.5
    - rvm: ruby-head
    - rvm: 2.6.5
      install: true # This skips 'bundle install'
      script: gem build *.gemspec && gem install *.gem
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
